apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: agent-ds
  namespace: system
spec:
  selector:
    matchLabels:
      raven.openyurt.io/agent: "true"
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 5%
  template:
    metadata:
      labels:
        raven.openyurt.io/agent: "true"
    spec:
      hostNetwork: true
      serviceAccountName: agent-account
      containers:
        - name: raven-agent
          image: raven-agent:latest
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VPN_CONNECTION_PSK
              valueFrom:
                secretKeyRef:
                  name: agent-secret
                  key: vpn-connection-psk
            - name: VPN_DRIVER
              valueFrom:
                configMapKeyRef:
                  name: agent-config
                  key: vpn-driver
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              httpHeaders:
                - name: OpenYurt-Header
                  value: raven-agent
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3